apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    name: hello-world-pod
    app: hello-world-app
spec:
  containers:
    -  name: hello-world-pod
       image: frankc60/hello-world    
       imagePullPolicy: Always
       terminationMessagePath: "/tmp/my-log"
