apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    name: hello-world-service
    app: hello-world-app
spec:
  type: NodePort
  ports:
    -  port: 3000
       targetPort: 3000
       nodePort: 30005
  selector:
      app: hello-world-app
